/**
 * scratch/test_db_save.js
 *
 * Reproduces and verifies the fix for:
 * "SQLite Engine Error during Bulk Insert: Wrong API use : tried to bind a value of an unknown type (undefined)."
 */

const fs = require("fs");
const vm = require("vm");
const path = require("path");
const assert = require("assert");

const workspaceDir = "/home/shashi/Desktop/WorkingArea/Spreadsheet";

function loadScript(filename) {
	return fs.readFileSync(path.join(workspaceDir, filename), "utf8");
}

const allCode = [
	loadScript("Constants.js"),
	loadScript("Datastructure.js"),
	loadScript("CellStore.js"),
	loadScript("Command.js"),
	loadScript("CommandManager.js"),
	loadScript("SpreadsheetModel.js"),
	loadScript("SelectionModel.js"),
	loadScript("GridRenderer.js"),
	loadScript("DbOps.js"),
	loadScript("SpreadsheetService.js"),
	`
	globalThis.AVLTree = AVLTree;
	globalThis.CellStore = CellStore;
	globalThis.AVLCellStore = AVLCellStore;
	globalThis.Command = Command;
	globalThis.SetCellCommand = SetCellCommand;
	globalThis.ClearRangeCommand = ClearRangeCommand;
	globalThis.CompoundCommand = CompoundCommand;
	globalThis.CommandManager = CommandManager;
	globalThis.GridRenderer = GridRenderer;
	globalThis.Spreadsheet = Spreadsheet;
	globalThis.SpreadsheetModel = SpreadsheetModel;
	globalThis.SelectionModel = SelectionModel;
	globalThis.DatabaseService = DatabaseService;
	globalThis.BackendService = BackendService;
	`,
].join("\n;\n");

const sandbox = {
	console,
	initSqlJs: require(path.join(workspaceDir, "sql.js")),
	alert: (msg) => console.log("[ALERT]", msg),
	window: {},
	document: {},
};
sandbox.globalThis = sandbox;
sandbox.window = sandbox;

vm.createContext(sandbox);
vm.runInContext(allCode, sandbox);

async function Run() {
	console.log("=== Testing In-Memory Spreadsheet Database Save ===");

	const SQL = await sandbox.initSqlJs();
	const db = new SQL.Database();
	const schemaSql = fs.readFileSync(
		path.join(workspaceDir, "schema.sql"),
		"utf8",
	);
	db.run(schemaSql);

	const dbService = new sandbox.DatabaseService();
	await dbService.Initialize();

	const backendService = new sandbox.BackendService(dbService);
	backendService.databaseService = dbService;

	const model = new sandbox.SpreadsheetModel();
	const sheet = model.CreateBlank("TestBlankSheet", 10, 5);

	// Case 1: Apply formatting with NO value passed (value: undefined in command)
	const cellCmd = new sandbox.SetCellCommand(
		model,
		1,
		0,
		undefined, // No value passed, only style!
		{ backgroundColor: "#ff0000" },
	);
	cellCmd.Execute();

	// Case 2: Normal cell with string value
	model.SetCell(2, 1, "Hello World", {});

	// Check cell data array generated by CellStore
	const dataArray = sheet.CellStore.ToDataArray();
	console.log("Generated data array for DB bulk insert:", dataArray);

	for (const row of dataArray) {
		assert.notStrictEqual(
			row.col_id,
			undefined,
			"col_id must not be undefined",
		);
		assert.notStrictEqual(
			row.row_id,
			undefined,
			"row_id must not be undefined",
		);
		assert.notStrictEqual(
			row.cell_value,
			undefined,
			"cell_value must not be undefined",
		);
		assert.notStrictEqual(
			row.cell_style,
			undefined,
			"cell_style must not be undefined",
		);
	}

	// Prepare columns as SaveSpreadsheetToDb does
	sheet.columns = sheet.columns.map((col) =>
		typeof col === "string" && col.startsWith("C")
			? parseInt(col.substring(1), 10)
			: col,
	);

	// Perform the save
	console.log("Executing SaveSpreadsheetChanges...");
	await backendService.SaveSpreadsheetChanges(sheet);
	console.log("SaveSpreadsheetChanges completed successfully! ✅");

	// Verify data was written to _sheet_data table
	const checkData = dbService.db.exec("SELECT * FROM _sheet_data;");
	console.log("Stored _sheet_data rows count:", checkData[0]?.values?.length);
	console.log("Stored _sheet_data sample row:", checkData[0]?.values?.[0]);
	assert(
		checkData[0]?.values?.length >= 2,
		"Must have inserted at least 2 rows",
	);

	console.log(
		"\n🎉 ALL IN-MEMORY DATABASE SAVE TESTS PASSED! No undefined bindings. ✅\n",
	);
}

Run().catch((err) => {
	console.error("Test failed:", err);
	process.exit(1);
});
